# Generated by Django 4.2.1 on 2023-05-10 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="applications",
            table="applications",
        ),
        migrations.AlterModelTable(
            name="jobheaders",
            table="job_headers",
        ),
        migrations.AlterModelTable(
            name="jobs",
            table="jobs",
        ),
    ]
