# Generated by Django 4.2.1 on 2023-05-10 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_applications_table_alter_jobheaders_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applications",
            options={"verbose_name_plural": "applications"},
        ),
        migrations.AlterModelOptions(
            name="jobheaders",
            options={"verbose_name_plural": "job_headers"},
        ),
        migrations.AlterModelOptions(
            name="jobs",
            options={"verbose_name_plural": "jobs"},
        ),
    ]
