# Generated by Django 4.2.1 on 2023-05-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_alter_applications_options_alter_jobheaders_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobheaders",
            name="job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="headers",
                to="jobs.jobs",
            ),
        ),
    ]
